package utils

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"app-sistem-akuntansi/models"
	"gorm.io/gorm"
)

// JournalLogger handles logging for journal entry operations
type JournalLogger struct {
	db     *gorm.DB
	logger *log.Logger
}

// NewJournalLogger creates a new journal logger
func NewJournalLogger(db *gorm.DB) *JournalLogger {
	// Ensure logs directory exists before opening file
	logDir := "logs"
	if _, err := os.Stat(logDir); os.IsNotExist(err) {
		_ = os.MkdirAll(logDir, 0755)
	}

	// Create journal-specific log file
	journalPath := filepath.Join(logDir, "journal_entries.log")
	logFile, err := os.OpenFile(journalPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
	if err != nil {
		log.Printf("Warning: Could not create journal log file: %v", err)
		return &JournalLogger{
			db:     db,
			logger: log.New(os.Stdout, "[JOURNAL] ", log.LstdFlags|log.Lshortfile),
		}
	}

	return &JournalLogger{
		db:     db,
		logger: log.New(logFile, "[JOURNAL] ", log.LstdFlags|log.Lshortfile),
	}
}

// JournalLogLevel represents different log levels for journal logging
type JournalLogLevel int

const (
	JournalLogLevelDebug JournalLogLevel = iota
	JournalLogLevelInfo
	JournalLogLevelWarning
	JournalLogLevelError
)

// JournalLogEntry represents a structured log entry
type JournalLogEntry struct {
	Level         JournalLogLevel        `json:"level"`
	Message       string                 `json:"message"`
	JournalID     *uint                  `json:"journal_id,omitempty"`
	UserID        *uint                  `json:"user_id,omitempty"`
	Action        string                 `json:"action"`
	ReferenceType string                 `json:"reference_type,omitempty"`
	ReferenceID   *uint                  `json:"reference_id,omitempty"`
	Amount        *float64               `json:"amount,omitempty"`
	Context       map[string]interface{} `json:"context,omitempty"`
	Timestamp     time.Time              `json:"timestamp"`
	RequestID     string                 `json:"request_id,omitempty"`
	ClientIP      string                 `json:"client_ip,omitempty"`
}

// LogJournalCreation logs journal entry creation
func (jl *JournalLogger) LogJournalCreation(ctx context.Context, entry *models.JournalEntry) {
	userID, _ := GetUserIDFromContext(ctx)
	
	logEntry := JournalLogEntry{
		Level:         JournalLogLevelInfo,
		Message:       fmt.Sprintf("Journal entry created: %s", entry.Code),
		JournalID:     &entry.ID,
		UserID:        &userID,
		Action:        "CREATE",
		ReferenceType: entry.ReferenceType,
		ReferenceID:   entry.ReferenceID,
		Amount:        &entry.TotalDebit,
		Context: map[string]interface{}{
			"description":      entry.Description,
			"status":          entry.Status,
			"is_balanced":     entry.IsBalanced,
			"total_debit":     entry.TotalDebit,
			"total_credit":    entry.TotalCredit,
			"is_auto_generated": entry.IsAutoGenerated,
		},
		Timestamp: time.Now(),
		RequestID: GetRequestIDFromContext(ctx),
		ClientIP:  GetClientIPFromContext(ctx),
	}
	
	jl.writeLog(logEntry)
	jl.saveToDatabase(logEntry)
}

// LogJournalPosting logs journal entry posting
func (jl *JournalLogger) LogJournalPosting(ctx context.Context, entryID uint, userID uint) {
	logEntry := JournalLogEntry{
		Level:     JournalLogLevelInfo,
		Message:   fmt.Sprintf("Journal entry posted: ID %d", entryID),
		JournalID: &entryID,
		UserID:    &userID,
		Action:    "POST",
		Context: map[string]interface{}{
			"action_type": "posting",
		},
		Timestamp: time.Now(),
		RequestID: GetRequestIDFromContext(ctx),
		ClientIP:  GetClientIPFromContext(ctx),
	}
	
	jl.writeLog(logEntry)
	jl.saveToDatabase(logEntry)
}

// LogJournalReversal logs journal entry reversal
func (jl *JournalLogger) LogJournalReversal(ctx context.Context, originalID, reversalID uint, reason string) {
	userID, _ := GetUserIDFromContext(ctx)
	
	logEntry := JournalLogEntry{
		Level:     JournalLogLevelInfo,
		Message:   fmt.Sprintf("Journal entry reversed: Original ID %d, Reversal ID %d", originalID, reversalID),
		JournalID: &originalID,
		UserID:    &userID,
		Action:    "REVERSE",
		Context: map[string]interface{}{
			"original_id":  originalID,
			"reversal_id":  reversalID,
			"reason":       reason,
			"action_type":  "reversal",
		},
		Timestamp: time.Now(),
		RequestID: GetRequestIDFromContext(ctx),
		ClientIP:  GetClientIPFromContext(ctx),
	}
	
	jl.writeLog(logEntry)
	jl.saveToDatabase(logEntry)
}

// LogAccountBalanceUpdate logs account balance updates
func (jl *JournalLogger) LogAccountBalanceUpdate(ctx context.Context, accountID uint, oldBalance, newBalance float64, journalID uint) {
	userID, _ := GetUserIDFromContext(ctx)
	
	logEntry := JournalLogEntry{
		Level:     JournalLogLevelDebug,
		Message:   fmt.Sprintf("Account balance updated: Account %d, %.2f → %.2f", accountID, oldBalance, newBalance),
		JournalID: &journalID,
		UserID:    &userID,
		Action:    "BALANCE_UPDATE",
		Context: map[string]interface{}{
			"account_id":   accountID,
			"old_balance":  oldBalance,
			"new_balance":  newBalance,
			"change":       newBalance - oldBalance,
			"action_type":  "balance_update",
		},
		Timestamp: time.Now(),
		RequestID: GetRequestIDFromContext(ctx),
		ClientIP:  GetClientIPFromContext(ctx),
	}
	
	jl.writeLog(logEntry)
}

// LogValidationError logs validation errors
func (jl *JournalLogger) LogValidationError(ctx context.Context, journalID *uint, validationType string, error error) {
	userID, _ := GetUserIDFromContext(ctx)
	
	logEntry := JournalLogEntry{
		Level:     JournalLogLevelError,
		Message:   fmt.Sprintf("Journal validation failed: %s - %v", validationType, error),
		JournalID: journalID,
		UserID:    &userID,
		Action:    "VALIDATION_ERROR",
		Context: map[string]interface{}{
			"validation_type": validationType,
			"error":          error.Error(),
			"action_type":    "validation",
		},
		Timestamp: time.Now(),
		RequestID: GetRequestIDFromContext(ctx),
		ClientIP:  GetClientIPFromContext(ctx),
	}
	
	jl.writeLog(logEntry)
	jl.saveToDatabase(logEntry)
}

// LogProcessingInfo logs general processing information
func (jl *JournalLogger) LogProcessingInfo(ctx context.Context, message string, context map[string]interface{}) {
	userID, _ := GetUserIDFromContext(ctx)
	
	logEntry := JournalLogEntry{
		Level:     JournalLogLevelInfo,
		Message:   message,
		UserID:    &userID,
		Action:    "PROCESSING",
		Context:   context,
		Timestamp: time.Now(),
		RequestID: GetRequestIDFromContext(ctx),
		ClientIP:  GetClientIPFromContext(ctx),
	}
	
	jl.writeLog(logEntry)
}

// LogWarning logs warning messages
func (jl *JournalLogger) LogWarning(ctx context.Context, message string, context map[string]interface{}) {
	userID, _ := GetUserIDFromContext(ctx)
	
	logEntry := JournalLogEntry{
		Level:     JournalLogLevelWarning,
		Message:   message,
		UserID:    &userID,
		Action:    "WARNING",
		Context:   context,
		Timestamp: time.Now(),
		RequestID: GetRequestIDFromContext(ctx),
		ClientIP:  GetClientIPFromContext(ctx),
	}
	
	jl.writeLog(logEntry)
}

// writeLog writes log entry to file
func (jl *JournalLogger) writeLog(entry JournalLogEntry) {
	levelStr := map[JournalLogLevel]string{
		JournalLogLevelDebug:   "DEBUG",
		JournalLogLevelInfo:    "INFO",
		JournalLogLevelWarning: "WARNING",
		JournalLogLevelError:   "ERROR",
	}
	
	contextStr := ""
	if len(entry.Context) > 0 {
		contextStr = fmt.Sprintf(" | Context: %+v", entry.Context)
	}
	
	logMessage := fmt.Sprintf("[%s] %s | Action: %s | User: %v | RequestID: %s%s",
		levelStr[entry.Level],
		entry.Message,
		entry.Action,
		entry.UserID,
		entry.RequestID,
		contextStr,
	)
	
	jl.logger.Println(logMessage)
}

// saveToDatabase saves important log entries to database
func (jl *JournalLogger) saveToDatabase(entry JournalLogEntry) {
	// Only save important entries to database (INFO, WARNING, ERROR)
	if entry.Level == JournalLogLevelDebug {
		return
	}
	
	// Save to audit_logs table if available
	auditLog := models.AuditLog{
		TableName: "journal_entries",
		Action:    entry.Action,
		IPAddress: entry.ClientIP,
		UserAgent: "journal_system",
		CreatedAt: entry.Timestamp,
	}
	
	// Set UserID properly
	if entry.UserID != nil {
		auditLog.UserID = entry.UserID
	} else {
		defaultUserID := uint(1) // Default system user
		auditLog.UserID = &defaultUserID
	}
	
	if entry.JournalID != nil {
		auditLog.RecordID = *entry.JournalID
	}
	
	if err := jl.db.Create(&auditLog).Error; err != nil {
		jl.logger.Printf("Failed to save log to database: %v", err)
	}
}