package main

import (
	"fmt"
	"log"
	"time"

	"app-sistem-akuntansi/config"
	"app-sistem-akuntansi/database"
	"app-sistem-akuntansi/models"
	"github.com/shopspring/decimal"
	"gorm.io/gorm"
)

// BackfillMissingCOGS backfills COGS journal entries for sales that don't have them
func main() {
	log.Println("========================================")
	log.Println("🔧 BACKFILL MISSING COGS JOURNAL ENTRIES")
	log.Println("========================================")

	// Load configuration
	cfg := config.LoadConfig()
	log.Printf("Environment: %s", cfg.Environment)

	// Connect to database
	db := database.ConnectDB()
	log.Println("✅ Database connected")

	// Step 1: Find all INVOICED/PAID sales
	log.Println("\n📊 Step 1: Finding all INVOICED/PAID sales...")
	var allSales []models.Sale
	if err := db.Where("status IN ?", []string{"INVOICED", "PAID"}).
		Preload("Customer").
		Preload("SaleItems.Product").
		Order("id ASC").
		Find(&allSales).Error; err != nil {
		log.Fatalf("❌ Failed to load sales: %v", err)
	}
	log.Printf("   Found %d sales to check", len(allSales))

	// Step 2: Check which sales have COGS entries
	log.Println("\n🔍 Step 2: Checking existing COGS journal entries...")
	salesWithoutCOGS := []models.Sale{}
	salesWithCOGS := 0
	
	for _, sale := range allSales {
		// Check if COGS journal exists for this sale
		var count int64
		db.Model(&models.SSOTJournalEntry{}).
			Where("source_type = ? AND source_id = ?", "SALE", sale.ID).
			Joins("JOIN unified_journal_lines ujl ON ujl.journal_id = unified_journal_ledger.id").
			Joins("JOIN accounts a ON a.id = ujl.account_id").
			Where("a.code = ?", "5101"). // COGS account
			Count(&count)
		
		if count == 0 {
			salesWithoutCOGS = append(salesWithoutCOGS, sale)
		} else {
			salesWithCOGS++
		}
	}
	
	log.Printf("   ✓ Sales with COGS: %d", salesWithCOGS)
	log.Printf("   ✗ Sales without COGS: %d", len(salesWithoutCOGS))

	if len(salesWithoutCOGS) == 0 {
		log.Println("\n✅ All sales already have COGS entries. Nothing to do!")
		return
	}

	// Step 3: Auto-proceed (for automated fix)
	log.Println("\n⚠️  Creating COGS journal entries for sales without them...")
	log.Println("    This operation will:")
	log.Println("    1. Create journal entries: Dr. COGS (5101), Cr. Inventory (1301)")
	log.Println("    2. Update account balances automatically")
	log.Println("    3. Fix your Profit & Loss report")
	log.Println("\n   (Auto-proceeding to fix accounting data...)\n")

	// Step 4: Process each sale
	log.Println("\n🔄 Step 3: Creating COGS journal entries...")
	successCount := 0
	failCount := 0
	zeroCogsCount := 0
	totalCOGSAmount := decimal.Zero

	for i, sale := range salesWithoutCOGS {
		log.Printf("\n[%d/%d] Processing Sale #%d (%s)...", 
			i+1, len(salesWithoutCOGS), sale.ID, sale.InvoiceNumber)

		// Calculate COGS for this sale
		var saleCOGS decimal.Decimal
		validItems := 0
		
		for _, item := range sale.SaleItems {
			if item.Product.ID == 0 {
				log.Printf("   ⚠️  Item #%d has no product loaded, skipping", item.ID)
				continue
			}
			
			itemCOGS := decimal.NewFromFloat(float64(item.Quantity)).
				Mul(decimal.NewFromFloat(item.Product.CostPrice))
			
			if itemCOGS.IsZero() {
				log.Printf("   ⚠️  Product '%s' has zero cost price", item.Product.Name)
			} else {
				saleCOGS = saleCOGS.Add(itemCOGS)
				validItems++
				log.Printf("   + %s: Qty %d × Rp %.2f = Rp %.2f", 
					item.Product.Name, item.Quantity, item.Product.CostPrice, itemCOGS.InexactFloat64())
			}
		}

		if saleCOGS.IsZero() {
			log.Printf("   ⚠️  SKIP: No COGS calculated (all items have zero cost price)")
			zeroCogsCount++
			continue
		}

		log.Printf("   💰 Total COGS: Rp %.2f (%d valid items)", saleCOGS.InexactFloat64(), validItems)

		// Create COGS journal entry using transaction
		err := db.Transaction(func(tx *gorm.DB) error {
			// We'll manually create the COGS journal since we need to append to existing journal
			// Get accounts
			var cogsAccount, inventoryAccount models.Account
			if err := tx.Where("code = ?", "5101").First(&cogsAccount).Error; err != nil {
				return fmt.Errorf("COGS account not found: %v", err)
			}
			if err := tx.Where("code = ?", "1301").First(&inventoryAccount).Error; err != nil {
				return fmt.Errorf("Inventory account not found: %v", err)
			}

			// Create separate COGS journal entry
			sourceID := uint64(sale.ID)
			now := time.Now()
			
			journalEntry := &models.SSOTJournalEntry{
				EntryNumber:     fmt.Sprintf("COGS-BACKFILL-%d-%d", sale.ID, now.Unix()),
				SourceType:      "SALE",
				SourceID:        &sourceID,
				SourceCode:      sale.InvoiceNumber,
				EntryDate:       sale.Date,
				Description:     fmt.Sprintf("COGS Backfill - %s", sale.InvoiceNumber),
				Reference:       fmt.Sprintf("BACKFILL-%s", sale.InvoiceNumber),
				TotalDebit:      saleCOGS,
				TotalCredit:     saleCOGS,
				Status:          "POSTED",
				IsBalanced:      true,
				IsAutoGenerated: true,
				PostedAt:        &now,
				PostedBy:        nil,
				CreatedBy:       1, // System
				CreatedAt:       now,
				UpdatedAt:       now,
			}

			if err := tx.Create(journalEntry).Error; err != nil {
				return fmt.Errorf("failed to create journal entry: %v", err)
			}

			// Create journal lines
			// Line 1: DEBIT COGS
			if err := tx.Create(&models.SSOTJournalLine{
				JournalID:    journalEntry.ID,
				AccountID:    uint64(cogsAccount.ID),
				LineNumber:   1,
				Description:  fmt.Sprintf("HPP - %s", sale.InvoiceNumber),
				DebitAmount:  saleCOGS,
				CreditAmount: decimal.Zero,
				CreatedAt:    now,
				UpdatedAt:    now,
			}).Error; err != nil {
				return fmt.Errorf("failed to create COGS line: %v", err)
			}

			// Line 2: CREDIT Inventory
			if err := tx.Create(&models.SSOTJournalLine{
				JournalID:    journalEntry.ID,
				AccountID:    uint64(inventoryAccount.ID),
				LineNumber:   2,
				Description:  fmt.Sprintf("Pengurangan Persediaan - %s", sale.InvoiceNumber),
				DebitAmount:  decimal.Zero,
				CreditAmount: saleCOGS,
				CreatedAt:    now,
				UpdatedAt:    now,
			}).Error; err != nil {
				return fmt.Errorf("failed to create inventory line: %v", err)
			}

			// Update account balances
			// COGS (expense) - debit increases
			cogsAccount.Balance += saleCOGS.InexactFloat64()
			if err := tx.Save(&cogsAccount).Error; err != nil {
				return fmt.Errorf("failed to update COGS balance: %v", err)
			}

			// Inventory (asset) - credit decreases
			inventoryAccount.Balance -= saleCOGS.InexactFloat64()
			if err := tx.Save(&inventoryAccount).Error; err != nil {
				return fmt.Errorf("failed to update inventory balance: %v", err)
			}

			return nil
		})

		if err != nil {
			log.Printf("   ❌ FAILED: %v", err)
			failCount++
		} else {
			log.Printf("   ✅ SUCCESS: COGS journal created")
			successCount++
			totalCOGSAmount = totalCOGSAmount.Add(saleCOGS)
		}
	}

	// Summary
	log.Println("\n========================================")
	log.Println("📊 BACKFILL SUMMARY")
	log.Println("========================================")
	log.Printf("Total Sales Checked:        %d", len(allSales))
	log.Printf("Sales with COGS (before):   %d", salesWithCOGS)
	log.Printf("Sales without COGS:         %d", len(salesWithoutCOGS))
	log.Printf("---")
	log.Printf("✅ Successfully Created:     %d", successCount)
	log.Printf("❌ Failed:                   %d", failCount)
	log.Printf("⚠️  Skipped (zero COGS):     %d", zeroCogsCount)
	log.Printf("---")
	log.Printf("💰 Total COGS Added:         Rp %.2f", totalCOGSAmount.InexactFloat64())
	log.Println("========================================")

	if successCount > 0 {
		log.Println("\n✅ Backfill completed successfully!")
		log.Println("   Your Profit & Loss report should now show correct COGS amounts.")
		log.Println("   Please verify by running the P&L report again.")
	}

	if zeroCogsCount > 0 {
		log.Printf("\n⚠️  WARNING: %d sales have zero COGS because products have no cost price.", zeroCogsCount)
		log.Println("   Run 'go run cmd/scripts/fix_product_cost_prices.go' to fix this.")
	}
}
