package main

import (
	"fmt"
	"log"
	"time"

	"app-sistem-akuntansi/config"
	"app-sistem-akuntansi/database"
	"app-sistem-akuntansi/models"
	"github.com/shopspring/decimal"
	"gorm.io/gorm"
)

func main() {
	fmt.Println("🚀 Full Migration to SSOT Journal System")
	fmt.Println("========================================")
	fmt.Println("This will:")
	fmt.Println("1. Migrate existing journal_entries data to SSOT")
	fmt.Println("2. Remove old journal tables and routes")  
	fmt.Println("3. Make SSOT the only journal system")
	fmt.Println("")

	_ = config.LoadConfig()
	db := database.ConnectDB()

	fmt.Println("✅ Database connected successfully")

	// Step 1: Backup and migrate existing journal data
	fmt.Println("\n1. 📦 Backing up and migrating existing journal data...")
	if err := migrateJournalEntriesToSSOT(db); err != nil {
		log.Fatalf("Migration failed: %v", err)
	}

	// Step 2: Verify migration success
	fmt.Println("\n2. ✅ Verifying migration...")
	if err := verifyMigration(db); err != nil {
		log.Fatalf("Verification failed: %v", err)
	}

	// Step 3: Archive old tables (rename, don't drop immediately for safety)
	fmt.Println("\n3. 📚 Archiving old journal tables...")
	if err := archiveOldTables(db); err != nil {
		log.Printf("Warning: Failed to archive tables: %v", err)
	}

	// Step 4: Update migration log
	fmt.Println("\n4. 📝 Updating migration records...")
	updateMigrationLog(db)

	// Step 5: Refresh materialized view
	fmt.Println("\n5. 🔄 Refreshing account balances...")
	db.Exec("REFRESH MATERIALIZED VIEW account_balances")

	fmt.Println("\n🎉 Full SSOT Migration Completed Successfully!")
	fmt.Println("============================================")
	fmt.Println("✅ All journal data migrated to SSOT")
	fmt.Println("✅ Old tables archived (not deleted for safety)")
	fmt.Println("✅ SSOT is now the single journal system")
	fmt.Println("✅ Account balances updated")
	
	fmt.Println("\n📊 Final Status:")
	printFinalStatus(db)
	
	fmt.Println("\n💡 Next Steps:")
	fmt.Println("• Update frontend to use /api/v1/journals endpoints")
	fmt.Println("• Test all journal operations via SSOT")
	fmt.Println("• Remove old journal routes from codebase")
	fmt.Println("• Monitor system performance")
	fmt.Println("• After 1-2 weeks, consider dropping archived tables")
}

func migrateJournalEntriesToSSOT(db *gorm.DB) error {
	// Start transaction
	tx := db.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// Get all journal entries to migrate
	var oldEntries []struct {
		ID               uint64
		Description      string
		EntryDate        time.Time
		TotalDebit       decimal.Decimal
		TotalCredit      decimal.Decimal
		Status           string
		Reference        *string
		Notes            *string
		CreatedAt        time.Time
		UpdatedAt        time.Time
		UserID           uint64
		PostedBy         *uint64
		PostingDate      *time.Time
		IsBalanced       bool
		IsAutoGenerated  bool
	}

	err := tx.Raw(`
		SELECT id, description, entry_date, total_debit, total_credit, status,
		       reference, notes, created_at, updated_at, user_id, posted_by,
		       posting_date, is_balanced, is_auto_generated
		FROM journal_entries 
		ORDER BY created_at
	`).Scan(&oldEntries).Error

	if err != nil {
		tx.Rollback()
		return fmt.Errorf("failed to read old journal entries: %v", err)
	}

	fmt.Printf("   Found %d journal entries to migrate\n", len(oldEntries))

	migratedCount := 0
	for _, oldEntry := range oldEntries {
		// Generate entry number
		entryNumber := fmt.Sprintf("JE-%s-%06d", 
			oldEntry.EntryDate.Format("2006"), oldEntry.ID)

		// Create unified journal entry
		newEntry := &models.SSOTJournalEntry{
			EntryNumber:      entryNumber,
			SourceType:       "MIGRATED", // Mark as migrated
			EntryDate:        oldEntry.EntryDate,
			Description:      oldEntry.Description,
			Reference:        stringPtrToString(oldEntry.Reference),
			Notes:            stringPtrToString(oldEntry.Notes),
			TotalDebit:       oldEntry.TotalDebit,
			TotalCredit:      oldEntry.TotalCredit,
			Status:           oldEntry.Status,
			IsBalanced:       oldEntry.IsBalanced,
			IsAutoGenerated:  oldEntry.IsAutoGenerated,
			CreatedBy:        oldEntry.UserID,
			CreatedAt:        oldEntry.CreatedAt,
			UpdatedAt:        oldEntry.UpdatedAt,
		}

		// Set posting information if entry was posted
		if oldEntry.Status == "POSTED" && oldEntry.PostingDate != nil {
			newEntry.PostedAt = oldEntry.PostingDate
			if oldEntry.PostedBy != nil {
				newEntry.PostedBy = oldEntry.PostedBy
			}
		}

		// Insert new entry
		if err := tx.Create(newEntry).Error; err != nil {
			tx.Rollback()
			return fmt.Errorf("failed to create migrated entry %d: %v", oldEntry.ID, err)
		}

		// Try to get lines from old journal structure
		// Note: The old journal_entries table seems to be storing everything in one record
		// We need to create lines based on the description and amounts
		lines := createLinesFromOldEntry(oldEntry, tx)
		
		// Create journal lines
		for i, line := range lines {
			newLine := &models.SSOTJournalLine{
				JournalID:    newEntry.ID,
				AccountID:    line.AccountID,
				LineNumber:   i + 1,
				Description:  line.Description,
				DebitAmount:  line.DebitAmount,
				CreditAmount: line.CreditAmount,
				CreatedAt:    oldEntry.CreatedAt,
				UpdatedAt:    oldEntry.UpdatedAt,
			}

			if err := tx.Create(newLine).Error; err != nil {
				tx.Rollback()
				return fmt.Errorf("failed to create line for entry %d: %v", oldEntry.ID, err)
			}
		}

		// Create event log entry
		eventLog := &models.SSOTJournalEventLog{
			JournalID:      &newEntry.ID,
			EventType:      "MIGRATED",
			EventData:      map[string]interface{}{
				"original_id": oldEntry.ID,
				"migrated_at": time.Now(),
				"source": "journal_entries_table",
			},
			EventTimestamp: time.Now(),
			UserID:         &oldEntry.UserID,
			UserRole:       "SYSTEM",
			IPAddress:      "127.0.0.1",
			UserAgent:      "Migration Script",
			SourceSystem:   "MIGRATION_SCRIPT",
			Metadata:       make(map[string]interface{}),
		}

		if err := tx.Create(eventLog).Error; err != nil {
			tx.Rollback()
			return fmt.Errorf("failed to create event log for entry %d: %v", oldEntry.ID, err)
		}

		migratedCount++
		if migratedCount%10 == 0 {
			fmt.Printf("   Migrated %d/%d entries...\n", migratedCount, len(oldEntries))
		}
	}

	// Commit transaction
	if err := tx.Commit().Error; err != nil {
		return fmt.Errorf("failed to commit migration: %v", err)
	}

	fmt.Printf("   ✅ Successfully migrated %d journal entries\n", migratedCount)
	return nil
}

func createLinesFromOldEntry(oldEntry struct {
	ID               uint64
	Description      string
	EntryDate        time.Time
	TotalDebit       decimal.Decimal
	TotalCredit      decimal.Decimal
	Status           string
	Reference        *string
	Notes            *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UserID           uint64
	PostedBy         *uint64
	PostingDate      *time.Time
	IsBalanced       bool
	IsAutoGenerated  bool
}, tx *gorm.DB) []struct {
	AccountID    uint64
	Description  string
	DebitAmount  decimal.Decimal
	CreditAmount decimal.Decimal
} {
	// Get default accounts from database
	var defaultDebitAccountID, defaultCreditAccountID uint64 = 1, 2
	
	// Try to get actual default accounts
	var debitAccount struct {
		ID uint64
	}
	tx.Raw("SELECT id FROM accounts WHERE type = 'ASSET' AND is_active = true LIMIT 1").Scan(&debitAccount)
	if debitAccount.ID > 0 {
		defaultDebitAccountID = debitAccount.ID
	}
	
	var creditAccount struct {
		ID uint64
	}
	tx.Raw("SELECT id FROM accounts WHERE type = 'LIABILITY' AND is_active = true LIMIT 1").Scan(&creditAccount)
	if creditAccount.ID > 0 {
		defaultCreditAccountID = creditAccount.ID
	}
	
	lines := []struct {
		AccountID    uint64
		Description  string
		DebitAmount  decimal.Decimal
		CreditAmount decimal.Decimal
	}{}

	// Create balanced entry - debit and credit must be equal
	amount := oldEntry.TotalDebit
	if oldEntry.TotalCredit.GreaterThan(amount) {
		amount = oldEntry.TotalCredit
	}
	
	if amount.GreaterThan(decimal.Zero) {
		// Add debit line
		lines = append(lines, struct {
			AccountID    uint64
			Description  string
			DebitAmount  decimal.Decimal
			CreditAmount decimal.Decimal
		}{
			AccountID:    defaultDebitAccountID,
			Description:  "[MIGRATED] " + oldEntry.Description,
			DebitAmount:  amount,
			CreditAmount: decimal.Zero,
		})
		
		// Add credit line
		lines = append(lines, struct {
			AccountID    uint64
			Description  string
			DebitAmount  decimal.Decimal
			CreditAmount decimal.Decimal
		}{
			AccountID:    defaultCreditAccountID,
			Description:  "[MIGRATED] " + oldEntry.Description,
			DebitAmount:  decimal.Zero,
			CreditAmount: amount,
		})
	}

	return lines
}

func stringPtrToString(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func verifyMigration(db *gorm.DB) error {
	// Count old entries
	var oldCount int64
	db.Raw("SELECT COUNT(*) FROM journal_entries").Scan(&oldCount)

	// Count new entries
	var newCount int64
	db.Raw("SELECT COUNT(*) FROM unified_journal_ledger WHERE source_type = 'MIGRATED'").Scan(&newCount)

	if oldCount != newCount {
		return fmt.Errorf("migration count mismatch: old=%d, new=%d", oldCount, newCount)
	}

	fmt.Printf("   ✅ Verified: %d entries migrated successfully\n", newCount)
	return nil
}

func archiveOldTables(db *gorm.DB) error {
	timestamp := time.Now().Format("20060102_150405")
	
	// Rename tables instead of dropping them
	tables := []string{
		"journal_entries",
		"journals", 
	}

	for _, table := range tables {
		// Check if table exists
		var exists bool
		db.Raw("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = ?)", table).Scan(&exists)
		
		if exists {
			archiveName := fmt.Sprintf("%s_archived_%s", table, timestamp)
			err := db.Exec(fmt.Sprintf("ALTER TABLE %s RENAME TO %s", table, archiveName)).Error
			if err != nil {
				return fmt.Errorf("failed to archive table %s: %v", table, err)
			}
			fmt.Printf("   ✅ Archived %s → %s\n", table, archiveName)
		} else {
			fmt.Printf("   ℹ️  Table %s not found (already archived?)\n", table)
		}
	}

	return nil
}

func updateMigrationLog(db *gorm.DB) {
	db.Exec(`
		INSERT INTO migration_logs (migration_name, status, message, execution_time_ms)
		VALUES ('full_migration_to_ssot', 'SUCCESS', 'Migrated all journal data to SSOT and archived old tables', 0)
		ON CONFLICT (migration_name) DO UPDATE SET
			status = EXCLUDED.status,
			message = EXCLUDED.message,
			executed_at = CURRENT_TIMESTAMP
	`)
	fmt.Println("   ✅ Migration log updated")
}

func printFinalStatus(db *gorm.DB) {
	// Count SSOT entries
	var ssotCount int64
	db.Raw("SELECT COUNT(*) FROM unified_journal_ledger").Scan(&ssotCount)

	// Count SSOT lines
	var linesCount int64
	db.Raw("SELECT COUNT(*) FROM unified_journal_lines").Scan(&linesCount)

	// Count event logs
	var eventsCount int64
	db.Raw("SELECT COUNT(*) FROM journal_event_log").Scan(&eventsCount)

	// Count account balances
	var balanceCount int64
	db.Raw("SELECT COUNT(*) FROM account_balances").Scan(&balanceCount)

	fmt.Printf("📊 SSOT System Status:\n")
	fmt.Printf("   Journal Entries: %d\n", ssotCount)
	fmt.Printf("   Journal Lines: %d\n", linesCount)
	fmt.Printf("   Event Logs: %d\n", eventsCount)
	fmt.Printf("   Account Balances: %d\n", balanceCount)
}