package models

import (
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"gorm.io/gorm"
)

// SSOTJournal is an alias for compatibility
type SSOTJournal = SSOTJournalEntry

// SSOTJournalItem is an alias for compatibility
type SSOTJournalItem = SSOTJournalLine

// SSOTJournalEntry represents a unified journal entry in the SSOT system
type SSOTJournalEntry struct {
	ID               uint64          `json:"id" gorm:"primaryKey;column:id"`
	EntryNumber      string          `json:"entry_number" gorm:"not null;size:50"`
	
	// Source Information
	SourceType       string          `json:"source_type" gorm:"not null;size:50;index"`
	SourceID         *uint64         `json:"source_id" gorm:"index"`
	SourceCode       string          `json:"source_code" gorm:"size:100"`
	
	// Journal Entry Details
	EntryDate        time.Time       `json:"entry_date" gorm:"not null;index"`
	Description      string          `json:"description" gorm:"not null;type:text"`
	Reference        string          `json:"reference" gorm:"size:200"`
	Notes            string          `json:"notes" gorm:"type:text"`
	
	// Financial Amounts
	TotalDebit       decimal.Decimal `json:"total_debit" gorm:"type:decimal(20,2);not null;default:0"`
	TotalCredit      decimal.Decimal `json:"total_credit" gorm:"type:decimal(20,2);not null;default:0"`
	
	// Status & Control Fields
	Status           string          `json:"status" gorm:"not null;default:DRAFT;size:20;index"`
	IsBalanced       bool            `json:"is_balanced" gorm:"not null;default:true"`
	IsAutoGenerated  bool            `json:"is_auto_generated" gorm:"not null;default:false"`
	
	// Posting Information
	PostedAt         *time.Time      `json:"posted_at" gorm:"index"`
	PostedBy         *uint64         `json:"posted_by" gorm:"index"`
	
	// Reversal Information
	ReversedBy       *uint64         `json:"reversed_by" gorm:"index"`   // Points to reversing entry
	ReversedFrom     *uint64         `json:"reversed_from" gorm:"index"` // Points to original entry
	ReversalReason   string          `json:"reversal_reason" gorm:"type:text"`
	
	// Audit Fields
	CreatedBy        uint64          `json:"created_by" gorm:"not null;index"`
	CreatedAt        time.Time       `json:"created_at" gorm:"not null;default:CURRENT_TIMESTAMP"`
	UpdatedAt        time.Time       `json:"updated_at" gorm:"not null;default:CURRENT_TIMESTAMP"`
	DeletedAt        *time.Time      `json:"deleted_at,omitempty" gorm:"index"`
	
	// Relations
	Lines            []SSOTJournalLine    `json:"lines,omitempty" gorm:"foreignKey:JournalID;constraint:OnDelete:CASCADE"`
	Creator          *User               `json:"creator,omitempty" gorm:"foreignKey:CreatedBy"`
	Poster           *User               `json:"poster,omitempty" gorm:"foreignKey:PostedBy"`
	ReversalEntry    *SSOTJournalEntry   `json:"reversal_entry,omitempty" gorm:"foreignKey:ReversedBy"`
	ReversedEntry    *SSOTJournalEntry   `json:"reversed_entry,omitempty" gorm:"foreignKey:ReversedFrom"`
}

// SSOTJournalLine represents individual debit/credit lines in a unified journal entry
type SSOTJournalLine struct {
	ID           uint64          `json:"id" gorm:"primaryKey;column:id"`
	JournalID    uint64          `json:"journal_id" gorm:"not null;index"`
	AccountID    uint64          `json:"account_id" gorm:"not null;index"`
	
	// Line Details
	LineNumber   int             `json:"line_number" gorm:"not null"`
	Description  string          `json:"description" gorm:"type:text"`
	
	// Financial Amounts (Mutually Exclusive)
	DebitAmount  decimal.Decimal `json:"debit_amount" gorm:"type:decimal(20,2);not null;default:0"`
	CreditAmount decimal.Decimal `json:"credit_amount" gorm:"type:decimal(20,2);not null;default:0"`
	
	// Additional Information for Inventory/Asset tracking
	Quantity     *decimal.Decimal `json:"quantity,omitempty" gorm:"type:decimal(15,4)"`
	UnitPrice    *decimal.Decimal `json:"unit_price,omitempty" gorm:"type:decimal(15,4)"`
	
	// Audit Fields
	CreatedAt    time.Time       `json:"created_at" gorm:"not null;default:CURRENT_TIMESTAMP"`
	UpdatedAt    time.Time       `json:"updated_at" gorm:"not null;default:CURRENT_TIMESTAMP"`
	
	// Relations
	Journal      *SSOTJournalEntry `json:"journal,omitempty" gorm:"foreignKey:JournalID"`
	Account      *Account         `json:"account,omitempty" gorm:"foreignKey:AccountID"`
}

// SSOTJournalEventLog represents audit trail for journal events
type SSOTJournalEventLog struct {
	ID              uint64          `json:"id" gorm:"primaryKey;column:id"`
	EventUUID       string          `json:"event_uuid" gorm:"type:uuid;uniqueIndex;not null"`
	JournalID       *uint64         `json:"journal_id" gorm:"index"`
	
	// Event Details
	EventType       string          `json:"event_type" gorm:"not null;size:50;index"`
	EventData       map[string]interface{} `json:"event_data" gorm:"type:jsonb;not null"`
	EventTimestamp  time.Time       `json:"event_timestamp" gorm:"not null;default:CURRENT_TIMESTAMP;index"`
	
	// User Context
	UserID          *uint64         `json:"user_id" gorm:"index"`
	UserRole        string          `json:"user_role" gorm:"size:50"`
	IPAddress       string          `json:"ip_address" gorm:"type:inet"`
	UserAgent       string          `json:"user_agent" gorm:"type:text"`
	
	// System Context
	SourceSystem    string          `json:"source_system" gorm:"size:50;default:ACCOUNTING_SYSTEM"`
	CorrelationID   *uuid.UUID      `json:"correlation_id" gorm:"type:uuid;index"`
	Metadata        map[string]interface{} `json:"metadata,omitempty" gorm:"type:jsonb"`
	
	// Relations
	Journal         *SSOTJournalEntry `json:"journal,omitempty" gorm:"foreignKey:JournalID"`
	User            *User             `json:"user,omitempty" gorm:"foreignKey:UserID"`
}

// SSOTAccountBalance represents real-time account balance view
type SSOTAccountBalance struct {
	AccountID           uint64          `json:"account_id" gorm:"primaryKey;column:account_id"`
	AccountCode         string          `json:"account_code" gorm:"column:account_code"`
	AccountName         string          `json:"account_name" gorm:"column:account_name"`
	AccountType         string          `json:"account_type" gorm:"column:account_type"`
	AccountCategory     string          `json:"account_category" gorm:"column:account_category"`
	NormalBalance       string          `json:"normal_balance" gorm:"column:normal_balance"`
	
	TotalDebits         decimal.Decimal `json:"total_debits" gorm:"column:total_debits"`
	TotalCredits        decimal.Decimal `json:"total_credits" gorm:"column:total_credits"`
	TransactionCount    int64           `json:"transaction_count" gorm:"column:transaction_count"`
	CurrentBalance      decimal.Decimal `json:"current_balance" gorm:"column:current_balance"`
	
	LastTransactionDate *time.Time      `json:"last_transaction_date" gorm:"column:last_transaction_date"`
	LastUpdated         time.Time       `json:"last_updated" gorm:"column:last_updated"`
	IsActive            bool            `json:"is_active" gorm:"column:is_active"`
	IsHeader            bool            `json:"is_header" gorm:"column:is_header"`
}

// TableName specifies the table names for the SSOT models
func (SSOTJournalEntry) TableName() string {
	return "unified_journal_ledger"
}

func (SSOTJournalLine) TableName() string {
	return "unified_journal_lines"
}

func (SSOTJournalEventLog) TableName() string {
	return "journal_event_log"
}

// Ensure UUID is set from application side to avoid DB extension dependency
func (e *SSOTJournalEventLog) BeforeCreate(tx *gorm.DB) error {
	if e.EventUUID == "" {
		e.EventUUID = uuid.New().String()
	}
	return nil
}

func (SSOTAccountBalance) TableName() string {
	return "account_balances"
}

// SSOT Constants for journal entry status
const (
	SSOTStatusDraft     = "DRAFT"
	SSOTStatusPosted    = "POSTED"
	SSOTStatusReversed  = "REVERSED"
	SSOTStatusCancelled = "CANCELLED"
)

// SSOT Constants for source types
const (
	SSOTSourceTypeSale         = "SALE"
	SSOTSourceTypePurchase     = "PURCHASE"
	SSOTSourceTypePayment      = "PAYMENT"
	SSOTSourceTypeCashBank     = "CASH_BANK"
	SSOTSourceTypeAsset        = "ASSET"
	SSOTSourceTypeManual       = "MANUAL"
	SSOTSourceTypeOpening      = "OPENING"
	SSOTSourceTypeClosing      = "CLOSING"
	SSOTSourceTypeAdjustment   = "ADJUSTMENT"
	SSOTSourceTypeTransfer     = "TRANSFER"
	SSOTSourceTypeDepreciation = "DEPRECIATION"
	SSOTSourceTypeReversal     = "REVERSAL"
)

// SSOT Constants for event types
const (
	SSOTEventTypeCreated   = "CREATED"
	SSOTEventTypePosted    = "POSTED"
	SSOTEventTypeReversed  = "REVERSED"
	SSOTEventTypeUpdated   = "UPDATED"
	SSOTEventTypeDeleted   = "DELETED"
	SSOTEventTypeBalanced  = "BALANCED"
	SSOTEventTypeValidated = "VALIDATED"
	SSOTEventTypeMigrated  = "MIGRATED"
	SSOTEventTypeSystem    = "SYSTEM_ACTION"
)

// Request/Response DTOs for SSOT
type SSOTJournalEntryCreateRequest struct {
	SourceType      string                      `json:"source_type" binding:"required"`
	SourceID        *uint64                     `json:"source_id"`
	SourceCode      string                      `json:"source_code"`
	EntryDate       time.Time                   `json:"entry_date" binding:"required"`
	Description     string                      `json:"description" binding:"required"`
	Reference       string                      `json:"reference"`
	Notes           string                      `json:"notes"`
	IsAutoGenerated bool                        `json:"is_auto_generated"`
	Lines           []SSOTJournalLineRequest    `json:"lines" binding:"required,min=2"`
}

type SSOTJournalLineRequest struct {
	AccountID     uint64           `json:"account_id" binding:"required"`
	Description   string           `json:"description"`
	DebitAmount   *decimal.Decimal `json:"debit_amount"`
	CreditAmount  *decimal.Decimal `json:"credit_amount"`
	Quantity      *decimal.Decimal `json:"quantity"`
	UnitPrice     *decimal.Decimal `json:"unit_price"`
}

type SSOTJournalEntryUpdateRequest struct {
	Description *string                   `json:"description"`
	Reference   *string                   `json:"reference"`
	EntryDate   *time.Time                `json:"entry_date"`
	Notes       *string                   `json:"notes"`
	Lines       []SSOTJournalLineRequest  `json:"lines"`
}

type SSOTJournalEntryFilter struct {
	Status        string `json:"status" form:"status"`
	SourceType    string `json:"source_type" form:"source_type"`
	AccountID     string `json:"account_id" form:"account_id"`
	DateFrom      string `json:"date_from" form:"date_from"`
	DateTo        string `json:"date_to" form:"date_to"`
	Reference     string `json:"reference" form:"reference"`
	Description   string `json:"description" form:"description"`
	Page          int    `json:"page" form:"page"`
	Limit         int    `json:"limit" form:"limit"`
}

// GORM Hook to generate EntryNumber before create
// SIMPLIFIED: Use simple timestamp-based entry number for instant processing
func (j *SSOTJournalEntry) BeforeCreate(tx *gorm.DB) error {
	// If EntryNumber already set by service (from Settings sequence), do not override
	if j.EntryNumber != "" {
		return nil
	}
	// Fallback: generate timestamp-based entry number to ensure non-empty value
	now := time.Now()
	j.EntryNumber = fmt.Sprintf("JE-%s-%d", now.Format("20060102-150405"), now.UnixNano()%1000000000)
	return nil
}

// Helper methods for SSOT Journal Entry
func (j *SSOTJournalEntry) IsDraft() bool {
	return j.Status == SSOTStatusDraft
}

func (j *SSOTJournalEntry) IsPosted() bool {
	return j.Status == SSOTStatusPosted
}

func (j *SSOTJournalEntry) IsReversed() bool {
	return j.Status == SSOTStatusReversed
}

func (j *SSOTJournalEntry) IsCancelled() bool {
	return j.Status == SSOTStatusCancelled
}

func (j *SSOTJournalEntry) CanPost() bool {
	return j.Status == SSOTStatusDraft && j.IsBalanced
}

func (j *SSOTJournalEntry) CanReverse() bool {
	return j.Status == SSOTStatusPosted
}

// Validation methods
func (j *SSOTJournalEntry) ValidateBalance() bool {
	return j.TotalDebit.Equal(j.TotalCredit)
}

func (j *SSOTJournalEntry) CalculateTotals() {
	var totalDebit, totalCredit decimal.Decimal
	
	for _, line := range j.Lines {
		totalDebit = totalDebit.Add(line.DebitAmount)
		totalCredit = totalCredit.Add(line.CreditAmount)
	}
	
	j.TotalDebit = totalDebit
	j.TotalCredit = totalCredit
	j.IsBalanced = j.ValidateBalance()
}

// Helper methods for SSOT Journal Line
func (l *SSOTJournalLine) IsDebit() bool {
	return l.DebitAmount.GreaterThan(decimal.Zero) && l.CreditAmount.IsZero()
}

func (l *SSOTJournalLine) IsCredit() bool {
	return l.CreditAmount.GreaterThan(decimal.Zero) && l.DebitAmount.IsZero()
}

func (l *SSOTJournalLine) GetAmount() decimal.Decimal {
	if l.IsDebit() {
		return l.DebitAmount
	}
	return l.CreditAmount
}