/**
 * Trial Balance Export Utilities
 * 
 * Provides enhanced CSV and PDF export functionality for Trial Balance reports
 * Supports SSOT trial balance data formats
 */

import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { SSOTTrialBalanceData } from '../services/ssotTrialBalanceService';


/**
 * Enhanced CSV Export for Trial Balance
 * Generates professional CSV format with proper formatting and structure
 */
export function exportTrialBalanceToCSV(
  data: SSOTTrialBalanceData,
  options: {
    includeAccountDetails?: boolean;
    companyName?: string;
  } = {}
): string {
  const { includeAccountDetails = true, companyName } = options;
  
  const csvLines: string[] = [];
  
  // Helper function to escape CSV values
  const escapeCSV = (value: string | number | null | undefined): string => {
    if (value === null || value === undefined) return '';
    const str = String(value);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };
  
  // Helper function to format currency
  const formatCurrencyForCSV = (amount: number | null | undefined): string => {
    if (amount === null || amount === undefined || isNaN(Number(amount))) {
      return '0';
    }
    return Number(amount).toLocaleString('id-ID');
  };
  
  // Header section
  csvLines.push(escapeCSV(companyName || data.company?.name || 'PT. Sistem Akuntansi Indonesia'));
  csvLines.push('TRIAL BALANCE');
  csvLines.push(`As of: ${data.as_of_date || new Date().toISOString().split('T')[0]}`);
  csvLines.push(`Generated on: ${new Date().toLocaleString('id-ID')}`);
  csvLines.push(''); // Empty line
  
  // Summary section
  csvLines.push('FINANCIAL SUMMARY');
  csvLines.push('Category,Amount');
  csvLines.push(`Total Debits,${formatCurrencyForCSV(data.total_debits || 0)}`);
  csvLines.push(`Total Credits,${formatCurrencyForCSV(data.total_credits || 0)}`);
  csvLines.push(`Difference,${formatCurrencyForCSV(data.difference || 0)}`);
  csvLines.push(`Balanced,${data.is_balanced ? 'Yes' : 'No'}`);
  csvLines.push(''); // Empty line
  
  if (includeAccountDetails && data.accounts && data.accounts.length > 0) {
    // Detailed account breakdown
    csvLines.push('ACCOUNT DETAILS');
    csvLines.push('Account Code,Account Name,Account Type,Debit Balance,Credit Balance');
    
    // Group accounts by type for better organization
    const accountTypes = ['Asset', 'Liability', 'Equity', 'Revenue', 'Expense', 'Other'];
    
    accountTypes.forEach(accountType => {
      const accountsOfType = data.accounts.filter(acc => acc.account_type === accountType);
      
      if (accountsOfType.length > 0) {
        csvLines.push(''); // Empty line before each type
        csvLines.push(`${accountType.toUpperCase()} ACCOUNTS,,,`);
        
        accountsOfType.forEach(account => {
          csvLines.push([
            escapeCSV(account.account_code || ''),
            escapeCSV(account.account_name || ''),
            escapeCSV(account.account_type || ''),
            formatCurrencyForCSV(account.debit_balance || 0),
            formatCurrencyForCSV(account.credit_balance || 0)
          ].join(','));
        });
        
        // Subtotal for this account type
        const typeDebitTotal = accountsOfType.reduce((sum, acc) => sum + (acc.debit_balance || 0), 0);
        const typeCreditTotal = accountsOfType.reduce((sum, acc) => sum + (acc.credit_balance || 0), 0);
        
        csvLines.push(`Subtotal ${accountType},,,${formatCurrencyForCSV(typeDebitTotal)},${formatCurrencyForCSV(typeCreditTotal)}`);
      }
    });
    
    csvLines.push(''); // Empty line
    csvLines.push(`GRAND TOTAL,,,${formatCurrencyForCSV(data.total_debits || 0)},${formatCurrencyForCSV(data.total_credits || 0)}`);
  }
  
  // Footer
  csvLines.push('');
  csvLines.push('Generated by Sistem Akuntansi');
  csvLines.push(`Report Date: ${new Date().toLocaleString('id-ID')}`);
  csvLines.push(`Data Source: SSOT Trial Balance`);
  
  return csvLines.join('\n');
}

/**
 * Enhanced PDF Export for Trial Balance
 * Generates professional PDF report with proper formatting and branding
 */
export function exportTrialBalanceToPDF(
  data: SSOTTrialBalanceData,
  options: {
    companyName?: string;
    logoUrl?: string;
    includeAccountDetails?: boolean;
  } = {}
): jsPDF {
  const { companyName, includeAccountDetails = true } = options;
  
  // Initialize PDF
  const doc = new jsPDF('portrait', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  
  // Helper function to format currency for PDF
  const formatCurrencyForPDF = (amount: number | null | undefined): string => {
    if (amount === null || amount === undefined || isNaN(Number(amount))) {
      return 'Rp 0';
    }
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0
    }).format(Number(amount));
  };
  
  // Set fonts
  doc.setFont('helvetica');
  
  // Header section
  let yPosition = 20;
  
  // Company name
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  const company = companyName || data.company?.name || 'PT. Sistem Akuntansi Indonesia';
  doc.text(company, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 10;
  
  // Report title
  doc.setFontSize(14);
  doc.text('TRIAL BALANCE', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 8;
  
  // Date and status
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const asOfDate = data.as_of_date || new Date().toISOString().split('T')[0];
  doc.text(`As of: ${new Date(asOfDate).toLocaleDateString('id-ID')}`, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 6;
  
  // Balance status
  const balanceStatus = data.is_balanced ? '✓ Balanced' : '✗ Not Balanced';
  const statusColor = data.is_balanced ? [0, 128, 0] : [255, 0, 0];
  doc.setTextColor(...statusColor);
  doc.text(balanceStatus, pageWidth / 2, yPosition, { align: 'center' });
  doc.setTextColor(0, 0, 0); // Reset to black
  
  yPosition += 15;
  
  // Summary table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('FINANCIAL SUMMARY', 20, yPosition);
  yPosition += 5;
  
  const summaryData = [
    ['Total Debits', formatCurrencyForPDF(data.total_debits || 0)],
    ['Total Credits', formatCurrencyForPDF(data.total_credits || 0)],
    ['Difference', formatCurrencyForPDF(data.difference || 0)],
    ['Status', data.is_balanced ? 'Balanced' : 'Not Balanced']
  ];
  
  (doc as any).autoTable({
    startY: yPosition,
    head: [['Category', 'Amount']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [138, 43, 226], textColor: 255, fontStyle: 'bold' },
    bodyStyles: { fontSize: 11 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 20, right: 20 },
    columnStyles: {
      1: { halign: 'right' }
    }
  });
  
  yPosition = (doc as any).lastAutoTable.finalY + 10;
  
  if (includeAccountDetails && data.accounts && data.accounts.length > 0) {
    // Detailed breakdown
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('ACCOUNT DETAILS', 20, yPosition);
    yPosition += 5;
    
    // Group accounts by type
    const accountTypes = ['Asset', 'Liability', 'Equity', 'Revenue', 'Expense', 'Other'];
    
    accountTypes.forEach((accountType, typeIndex) => {
      const accountsOfType = data.accounts.filter(acc => acc.account_type === accountType);
      
      if (accountsOfType.length > 0) {
        // Check if we need a new page
        if (yPosition > pageHeight - 100) {
          doc.addPage();
          yPosition = 20;
        }
        
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(`${accountType.toUpperCase()} ACCOUNTS`, 20, yPosition);
        yPosition += 5;
        
        const typeData: any[] = [];
        
        accountsOfType.forEach(account => {
          typeData.push([
            account.account_code || '',
            account.account_name || '',
            account.debit_balance && account.debit_balance > 0 ? formatCurrencyForPDF(account.debit_balance) : '-',
            account.credit_balance && account.credit_balance > 0 ? formatCurrencyForPDF(account.credit_balance) : '-'
          ]);
        });
        
        // Add subtotal
        const typeDebitTotal = accountsOfType.reduce((sum, acc) => sum + (acc.debit_balance || 0), 0);
        const typeCreditTotal = accountsOfType.reduce((sum, acc) => sum + (acc.credit_balance || 0), 0);
        
        typeData.push([
          `Subtotal ${accountType}`,
          '',
          formatCurrencyForPDF(typeDebitTotal),
          formatCurrencyForPDF(typeCreditTotal)
        ]);
        
        // Color scheme based on account type
        const typeColors: { [key: string]: number[] } = {
          'Asset': [40, 167, 69],
          'Liability': [255, 193, 7],
          'Equity': [23, 162, 184],
          'Revenue': [138, 43, 226],
          'Expense': [220, 53, 69],
          'Other': [108, 117, 125]
        };
        
        doc.autoTable({
          startY: yPosition,
          head: [['Account Code', 'Account Name', 'Debit', 'Credit']],
          body: typeData,
          theme: 'grid',
          headStyles: { 
            fillColor: typeColors[accountType] || [108, 117, 125], 
            textColor: 255, 
            fontStyle: 'bold' 
          },
          bodyStyles: { fontSize: 9 },
          alternateRowStyles: { fillColor: [248, 249, 250] },
          margin: { left: 20, right: 20 },
          columnStyles: {
            2: { halign: 'right' },
            3: { halign: 'right' }
          }
        });
        
        yPosition = (doc as any).lastAutoTable.finalY + 8;
      }
    });
    
    // Grand Total
    if (yPosition > pageHeight - 50) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('GRAND TOTAL', 20, yPosition);
    yPosition += 5;
    
    const grandTotalData = [
      [
        'TOTAL',
        '',
        formatCurrencyForPDF(data.total_debits || 0),
        formatCurrencyForPDF(data.total_credits || 0)
      ]
    ];
    
    doc.autoTable({
      startY: yPosition,
      head: [['', '', 'Total Debits', 'Total Credits']],
      body: grandTotalData,
      theme: 'grid',
      headStyles: { fillColor: [52, 58, 64], textColor: 255, fontStyle: 'bold' },
      bodyStyles: { fontSize: 11, fontStyle: 'bold' },
      margin: { left: 20, right: 20 },
      columnStyles: {
        2: { halign: 'right', fillColor: [248, 249, 250] },
        3: { halign: 'right', fillColor: [248, 249, 250] }
      }
    });
  }
  
  // Footer
  const footerY = pageHeight - 20;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Sistem Akuntansi', 20, footerY);
  doc.text(`Generated on: ${new Date().toLocaleString('id-ID')}`, pageWidth - 20, footerY, { align: 'right' });
  doc.text(`Data Source: SSOT Trial Balance`, pageWidth / 2, footerY, { align: 'center' });
  
  // Add page numbers if multiple pages
  const pageCount = doc.getNumberOfPages();
  if (pageCount > 1) {
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, footerY - 5, { align: 'right' });
    }
  }
  
  return doc;
}

/**
 * Download CSV file
 */
export function downloadTrialBalanceCSV(csvContent: string, filename?: string): void {
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename || `trial_balance_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

/**
 * Download PDF file
 */
export function downloadTrialBalancePDF(doc: jsPDF, filename?: string): void {
  const pdfName = filename || `trial_balance_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(pdfName);
}

/**
 * Export Trial Balance as CSV and trigger download
 */
export function exportAndDownloadTrialBalanceCSV(
  data: SSOTTrialBalanceData,
  options?: {
    includeAccountDetails?: boolean;
    companyName?: string;
    filename?: string;
  }
): void {
  const csvContent = exportTrialBalanceToCSV(data, options);
  downloadTrialBalanceCSV(csvContent, options?.filename);
}

/**
 * Export Trial Balance as PDF and trigger download
 */
export function exportAndDownloadTrialBalancePDF(
  data: SSOTTrialBalanceData,
  options?: {
    companyName?: string;
    logoUrl?: string;
    includeAccountDetails?: boolean;
    filename?: string;
  }
): void {
  const doc = exportTrialBalanceToPDF(data, options);
  downloadTrialBalancePDF(doc, options?.filename);
}
